name: 104souththird
favicon: null
layout_spectrum: 0.760525785619393
typography_spectrum: 0.08830060414038599
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef8fa'
    - '#807d78'
    - '#2d170a'
    - '#62462b'
    - '#ab9d8e'
  brandStrength: 0.030213624937459826
  lightness: 0.7539152584504336
  saturation: 0.9379993036855012
  rhythmicContrast: 0.5
purpose: []
